spring:
  application:
    name: meetcore
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/meetcore_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Admin1234}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
